### ISSUE TITLE
16Res数据集复现结果达不到论文结果的原因

### ISSUE THREAD

**Issue by FengLingCong13** [zzp-seeker/COM-MRC#1]
您好，我最近尝试复现了COM-MRC的实验，采用的是您的默认设置。V2版本中其他几个数据级都基本能达到您论文中的结果，但是16Res数据集只能复现出69.5（F1）的结果，和论文中相差2点多。请问这是什么原因？十分感谢您的解答。

**Comment by zzp-seeker** [comment]
可以更换随机种子试一下

**Comment by huna120** [comment]
> 您好，我最近尝试复现了COM-MRC的实验，采用的是您的默认设置。V2版本中其他几个数据级都基本能达到您论文中的结果，但是16Res数据集只能复现出69.5（F1）的结果，和论文中相差2点多。请问这是什么原因？十分感谢您的解答。

可以问问您的随机种子设的多少呀？我复现，结果相差很大
